# ClamAV configuration
LogFile /var/log/clamav/clamd.log
LogTime yes
LogFileMaxSize 10M
LogRotate yes
Debug yes
PidFile /var/run/clamav/clamd.pid
TemporaryDirectory /var/tmp
DatabaseDirectory /var/lib/clamav
OfficialDatabaseOnly yes
LocalSocket /var/run/clamav/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 0.0.0.0
MaxConnectionQueueLength 30
StreamMaxLength 100M
MaxFileSize 100M
MaxScanSize 100M
MaxRecursion 16
FollowDirectorySymlinks no
FollowFileSymlinks no
ReadTimeout 300
CommandReadTimeout 5
SendBufTimeout 200
MaxThreads 12
IdleTimeout 60
ScanOnAccess yes
ScanPE yes
ScanELF yes
DetectBrokenExecutables yes
ScanMail yes
ScanPartialMessages yes
PhishingSignatures yes
PhishingScanURLs yes
HeuristicScanPrecedence yes
StructuredDataDetection yes
ArchiveBlockEncrypted no
EngineMaxRecursion 16
EngineMaxRecursionArchive 10
EngineMaxRecursionDoc 8
EngineMaxRecursionHtml 8
EngineMaxRecursionMail 12
EngineMaxRecursionPdf 8
EngineBytecodeSignature yes
BytecodeSecurity TrustSigned
BytecodeTimeout 60000
OnAccessMaxFileSize 5M
OnAccessPrevention yes
OnAccessExtraScanning yes
OnAccessIncludePath /scan
VirusEvent /usr/bin/clamdscan --infected --remove --multiscan --move=/var/log/clamav/quarantine %f